title: Taller3
description: _
theme: jekyll-theme-cayman

site:
  name: Taller3
  description: Taller 3 de Software 2
  version: 1.0.0

pages:
  - path: /
    title: Página principal
    source: docs/index.md
    permalink: /
